@host=http://localhost:5202
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiSm9obiIsImVtYWlsIjoibWFyY2Vsb2NoYkBnbWFpbC5jb20iLCJqdGkiOiJjYmYwMDYxNi03ZTQ4LTQ2NTktYTMzOC02NDdhYmNjMTBkZDAiLCJsZWRnZXJJZCI6IjI2ODdkZTk4LWVkNDItNDJmNy04ZmYwLTZkY2E2ZTQ0ODk4NyIsImV4cCI6MTcwODY3NDA4OSwiaXNzIjoiQnVkZ2V0Q29udHJvbCIsImF1ZCI6IkJ1ZGdldENvbnRyb2wifQ.6QbgcUTGnBcElPeSLfwZEwy4flbBDTuNMBuq-GuHRnc
@id=2687de98-ed42-42f7-8ff0-6dca6e448987
GET {{host}}/ledgers/{{id}}
Authorization: Bearer {{token}}