@host=http://localhost:5202
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiTWFyY2VsbyBCbG9jayBUZWl4ZWlyYSIsImVtYWlsIjoibWFyY2Vsb2NoYkBnbWFpbC5jb20iLCJqdGkiOiIxN2E4ZWIzNi0zZjdlLTRkNTgtOTRlNy05ZmEyNjc1MTFlMGIiLCJleHAiOjE3MTU4Mjg5NTEsImlzcyI6IkJ1ZGdldENvbnRyb2wiLCJhdWQiOiJCdWRnZXRDb250cm9sIn0.l_Xlp_6m8n2uz4tvQMzsFRcTeuECE-PkkNS77reY930

@id=c1744b28-50ee-46b7-b674-d9d3c0d23ea0
GET {{host}}/ledgers/{{id}}
Authorization: Bearer {{token}}