@host=http://localhost:5202
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiSm9obiIsImVtYWlsIjoibWFyY2Vsb2NoYkBnbWFpbC5jb20iLCJqdGkiOiIxYjAzNjA0Ni1kNTQ5LTQ1OGMtOTIzNi01NTQxY2U0YWJhM2YiLCJleHAiOjE3MDcyNTMzMTcsImlzcyI6IkJ1ZGdldENvbnRyb2wiLCJhdWQiOiJCdWRnZXRDb250cm9sIn0.nj_QQOKcGJswBWmcgbcPPdrqyLJHUBzaOX_nl9v9be4
GET {{host}}/ledgers
Authorization: Bearer {{token}}
