@host=http://localhost:5202
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiSm9obiIsImVtYWlsIjoibWFyY2Vsb2NoYkBnbWFpbC5jb20iLCJqdGkiOiI5MDZiMWIxNC1iMGM0LTQ1MmMtYTk1MC01YjJhZmIwN2RhODkiLCJleHAiOjE3MDc0MzMzMzIsImlzcyI6IkJ1ZGdldENvbnRyb2wiLCJhdWQiOiJCdWRnZXRDb250cm9sIn0.PiIK2x-rOSAp5g6UtqZIqs_oZskHneSqW5_C2EkmvYA
GET {{host}}/ledgers
Authorization: Bearer {{token}}
