@host=http://localhost:5202
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiSm9obiIsImVtYWlsIjoibWFyY2Vsb2NoYkBnbWFpbC5jb20iLCJqdGkiOiI0ODAzMzk0YS0wNTQ1LTQ3YzgtYTc5ZC1mZjYwNDA1MzFlZWUiLCJleHAiOjE3MDcwNjI3NjksImlzcyI6IkJ1ZGdldENvbnRyb2wiLCJhdWQiOiJCdWRnZXRDb250cm9sIn0.vytXYOy-OSUijX14ojqyS9VHd5WcL5Ob3ONzUPKSlps
GET {{host}}/ledgers
Authorization: Bearer {{token}}
