@host=http://localhost:5202
POST {{host}}/auth/register
Content-Type: application/json

{
  "name": "Marcelo Block Teixeira",
  "email": "marcelochb@gmail.com",
  "password": "123456",
  "confirmPassword": "123456"
}