@host=http://localhost:5202
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiTWFyY2VsbyBCbG9jayBUZWl4ZWlyYSIsImVtYWlsIjoibWFyY2Vsb2NoYkBnbWFpbC5jb20iLCJqdGkiOiJjNmE3MmY4ZC02N2UxLTQzYTMtYjU3Mi1iZjkxMjRkYzFjZTgiLCJleHAiOjE3MTE4MzY2MDEsImlzcyI6IkJ1ZGdldENvbnRyb2wiLCJhdWQiOiJCdWRnZXRDb250cm9sIn0.-gqcDdYhndZEWMP9QuGTsrS_l9qneH0lB7GcfM1jLyQ
POST {{host}}/category
Authorization: Bearer {{token}}
Content-Type: application/json

  {
    "name": "Teste nova category",
    "goal": 100,
    "color": "#FF0000",
    "ledgerId": "79d926e4-7d51-41c6-b37c-a19ee5979d0b"
  }